services:
  service:
    container_name: service
    image: go-automate-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - service
    ports:
      - 80:80
    environment:
      DB_URL: database-mysql
    command: ["./main", "service"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health/check"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 15s
      start_interval: 5s
    depends_on:
      migration:
        condition: service_healthy

  migration:
    container_name: migration
    image: go-automate-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - migration
    command: sleep infinity
    environment:
      DB_URL: database-mysql
    healthcheck:
      test: ./main migration
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 5s
      start_interval: 5s
    depends_on:
      database-mysql:
        condition: service_healthy

  database-mysql:
    container_name: database-mysql
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - dependencies
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: automate-test
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysql --user=root --password=root --execute='show databases'
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
      start_interval: 5s
