services:
  database-mysql:
    container_name: database-mysql
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - dependencies
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: automate-test
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysql --user=root --password=root --execute='show databases'
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
      start_interval: 5s
